apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test
  namespace: local-cf-7
spec:
  entrypoint: whalesay
  templates:
    - name: main
      steps:
        - - name: whalesay
            template: whalesay
        - - name: exec-whalesay
            templateRef:
              name: whalesay
              template: main

    - name: whalesay
      container:
        image: docker/whalesay
        command:
          - cowsay
        args:
          - Hello World
