apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test
  namespace: local-cf-7
spec:
  entrypoint: echo
  templates:

  - name: echo
    inputs:
      parameters:
        - name: message
    container:
      image: alpine
      command:
        - echo
        - "{{inputs.parameters.message}}"


