apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: whalesay
  namespace: local-cf-5
spec:
  arguments: {}
  entrypoint: whalesay
  templates:
  - name: main
    steps:
      - - name: whalesay
          template: whalesay
      - - name: exec-whalesay-another
          templateRef:
            name: whalesay-another
            template: main
      - - name: exec-whalesay-cluster
          templateRef:
            name: whalesay-cluster
            template: main
            clusterScope: true

  - name: whalesay
    container:
      image: docker/whalesay
      command:
        - cowsay
      args:
        - Hello World
