apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: whalesay-another
  namespace: local-cf-4
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      args:
        - Hello World
      command:
        - cowsay
      image: docker/whalesay
